mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: "password"
  volumes:
   - "./docker-vols/mysql_lib:/var/lib/mysql"
   - "./docker-vols/mysql_tmp_cache:/tmp/cache"

memcached:
  image: memcached:1.4

mongo:
  image: mongo:2.4
  volumes:
    - "./docker-vols/mongo_data_db:/data/db"

lms:
  build: edxapp
  environment:
    PYTHONPATH: "/edx/app/edxapp/src/"
    DJANGO_SETTINGS_MODULE: lms.envs.docker

  # command: paver lms
  command: python manage.py lms runserver 0.0.0.0:8000

  volumes:
   - "/edx/app/edxapp/edx-platform:/edx/app/edxapp/edx-platform"

   - "./docker-vols/lms_edx_app_edxapp_edx_platform_src:/edx/app/edxapp/edx-platform/src/"
   - "./docker-vols/lms_edx_app_edxapp_staticfiles:/edx/app/edxapp/staticfiles/"

   - "./docker-vols/lms_edx_app_edxapp_log:/edx/app/edxapp/log"
   - "./docker-vols/lms_edx_var_edxapp_data:/edx/var/edxapp/data"
   - "./docker-vols/lms_edx_app_edxapp_uploads:/edx/app/edxapp/uploads"

   - "./edxapp/lms_docker_env.py:/edx/app/edxapp/edx-platform/lms/envs/docker.py"
   - "./edxapp/cms_docker_env.py:/edx/app/edxapp/edx-platform/cms/envs/docker.py"
   - "./edxapp/docker_common.py:/edx/app/edxapp/edx-platform/lms/envs/docker_common.py"
   - "./edxapp/docker_common.py:/edx/app/edxapp/edx-platform/cms/envs/docker_common.py"

  links:
   - mysql
   - mongo
   - memcached

studio:
  build: edxapp
  environment:
    PYTHONPATH: "/edx/app/edxapp/src/"
    DJANGO_SETTINGS_MODULE: cms.envs.docker

  # command: paver studio
  command: python manage.py cms runserver 0.0.0.0:8001

  volumes_from:
    - lms:rw

  links:
   - mysql
   - mongo
   - memcached

nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - lms
    - studio
