mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: "password"
  volumes_from:
    - "data:rw"

memcached:
  image: memcached:1.4

mongo:
  image: mongo:2.4
  volumes_from:
    - "data:rw"

lms:
  build: edxapp
  environment:
    PYTHONPATH: "/edx/app/edxapp/src/"
    DJANGO_SETTINGS_MODULE: lms.envs.docker

  command: paver lms
  # command: python manage.py lms runserver 0.0.0.0:8000

  volumes_from:
    - "data:rw"

  links:
   - mysql
   - mongo
   - memcached

studio:
  build: edxapp
  environment:
    PYTHONPATH: "/edx/app/edxapp/src/"
    DJANGO_SETTINGS_MODULE: cms.envs.docker

  command: paver studio
  # command: python manage.py cms runserver 0.0.0.0:8001

  volumes_from:
    - data:rw

  links:
   - mysql
   - mongo
   - memcached

data:
  image: busybox
  volumes:
    # MySQL
    - /var/lib/mysql
    - /tmp/cache

    # MongoDB
    - /data/db

    # edxapp
    - /edx/app/edxapp/staticfiles/
    - /edx/app/edxapp/log
    - /edx/var/edxapp/data
    - /edx/app/edxapp/uploads

nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - lms
    - studio
