mysql:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: "password"
  volumes_from:
    - "data:rw"


memcached:
  image: memcached:1.4


mongo:
  image: mongo:2.4
  volumes_from:
    - "data:rw"


lms:
  build: build/edxapp
  working_dir: /edx/app/edxapp/edx-platform
  expose:
    - "8000"
  command: paver lms --settings=devstack
  # command: python manage.py lms runserver 0.0.0.0:8000 --settings=devstack

  volumes_from:
    - "syslog:rw"

  volumes:
    - "../edx-platform/:/edx/app/edxapp/edx-platform-devcode"
    - "../envs-edx:/edx/app/edxapp/devenvs"

    - "/edx/app/edxapp/staticfiles"
    - "/edx/app/edxapp/log"
    - "/edx/var/edxapp/data"
    - "/edx/app/edxapp/uploads"
    - "/tmp/edx-s3/grades"

  links:
   - mysql
   - mongo
   - memcached


studio:
  build: build/edxapp
  working_dir: /edx/app/edxapp/edx-platform
  expose:
    - "8001"
  command: paver studio --settings=devstack
  # command: python manage.py cms runserver 0.0.0.0:8001 --settings=devstack

  volumes_from:
    - "lms:rw"

  links:
   - mysql
   - mongo
   - memcached


data:
  image: busybox
  volumes:
    # MySQL
    - /var/lib/mysql
    - /tmp/cache

    # MongoDB
    - /data/db


nginx:
  build: build/nginx
  ports:
    - "80:80"
  links:
    - lms
    - studio


# Provide a syslog just to make the devstack running!
syslog:
  image: edx-devstack-syslog
  volumes:
    - "/dev/"
    - "/var/log"
